# client-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
      - name: client
        image: your-docker-image-for-client:latest  # Replace with the actual image name for the client
        imagePullPolicy: Always
        ports:
        - containerPort: 8080  # Adjust the port if necessary
