apiVersion: v1
kind: Pod
metadata:
  name: client-pod
spec:
  containers:
    - name: client-container
      image: my_client_image
      # Você pode adicionar outros campos do Pod aqui, se necessário
