# Use a imagem base do sistema operacional que possui o compilador gcc instalado
FROM gcc:latest

# Copie o arquivo client.c para o container
COPY client.c /app/client.c

# Defina o diretório de trabalho para /app
WORKDIR /app

# Compile o arquivo client.c para um executável chamado client
RUN gcc -o client client.c

# Comando padrão a ser executado quando o container iniciar (neste caso, executará o cliente)
CMD ["./client"]
