# Use an appropriate base image with Python and required dependencies
FROM python:latest

WORKDIR /app

# Copy the server.py and other necessary files to the container
COPY server.py .
COPY openmp_mpi openmp_mpi  # Assuming the OpenMP and MPI code binary is named openmp_mpi
COPY jogo_vida.py jogo_vida.py  # Assuming the Apache Spark code file is named jogo_vida.py

CMD ["python", "server.py"]
