apiVersion: v1
kind: Service
metadata:
  name: server-service
spec:
  selector:
    # Use a mesma label que você usou no Pod do servidor
    app: server-pod
  ports:
    - name: tcp-port
      protocol: TCP
      port: 8080
      targetPort: 8080
