apiVersion: v1
kind: Pod
metadata:
  name: server-pod
spec:
  containers:
    - name: server-container
      image: my_server_image
      # Você pode adicionar outros campos do Pod aqui, se necessário
